# Generated by Django 4.2.23 on 2025-06-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('lounge_access', 'Lounge Access'), ('points_multiplier', 'Points Multiplier'), ('statement_credit', 'Statement Credit'), ('membership', 'Complimentary Membership'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
