# Generated by Django 4.2.23 on 2025-06-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefits', to='cards.benefit')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefits', to='cards.card')),
            ],
            options={
                'unique_together': {('card', 'display_name')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='benefits',
            field=models.ManyToManyField(related_name='cards', through='cards.CardBenefit', to='cards.benefit'),
        ),
    ]
