# Generated by Django 4.2.23 on 2025-06-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardbenefit_card_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cards.spendingcategory')),
            ],
            options={
                'verbose_name': 'Spending Category',
                'verbose_name_plural': 'Spending Categories',
                'ordering': ['name'],
            },
        ),
    ]
